<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://webservice.ws.altut.patent.siriusit.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="MXA" targetNamespace="http://webservice.ws.altut.patent.siriusit.com/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="MXA_schema1.xsd" namespace="http://webservice.ws.altut.patent.siriusit.com/" />
    </xsd:schema>
  </types>
  <message name="submitMessage">
    <part name="parameters" element="tns:submitMessage" />
  </message>
  <message name="submitMessageResponse">
    <part name="parameters" element="tns:submitMessageResponse" />
  </message>
  <portType name="MXADelegate">
    <operation name="submitMessage">
      <input message="tns:submitMessage" />
      <output message="tns:submitMessageResponse" />
    </operation>
  </portType>
  <binding name="MXAPortBinding" type="tns:MXADelegate">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="submitMessage">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  <service name="MXA">
    <port name="MXAPort" binding="tns:MXAPortBinding">
      <soap:address location="http://tst-mxa:8080/mxa/MXAPort" />
    </port>
  </service>
</definitions>