resources:
  repositories:
    - repository: efm-eproc-pipeline
      type: github
      name: felleslosninger/efm-eproc-pipeline
      endpoint: felleslosninger

trigger:
  batch: true
  branches:
    include:
      - development
      - release-*
      - master

steps:
  - template: build-and-deploy-template.yml@efm-eproc-pipeline
    parameters:
      environmentRepository: git://eformidling/eformidling
      jdkVersion: 1.8
      buildDockerArtifact: false
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: 'jacoco.exec'