pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: efm-eproc-pipeline
      type: github
      name: felleslosninger/efm-eproc-pipeline
      endpoint: felleslosninger
      ref: hotfix-build

extends:
  template: build-and-deploy-template.yml@efm-eproc-pipeline
  parameters:
    environmentRepository: git://eformidling/eformidling
    jdkVersion: 1.8
    coverageTool: none
    buildDockerArtifact: true
    dockerhubPush: true
    dockerRegistryEndpoint: dockerhub-difi
    deployOssrh: true
    mavenGoals: deploy
    jiraVersionPrefix: IP

trigger:
  batch: true
  branches:
    include:
      - '*'

pr: none
