<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="EDUImportService" targetNamespace="http://tempuri.org/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex"
                  xmlns:i0="http://www.arkivverket.no/Noark/Exchange"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:wsa10="http://www.w3.org/2005/08/addressing"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy"
                  xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"
                  xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tempuri.org/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
    <wsp:Policy wsu:Id="BasicHttpBinding_IEDUImport_policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <http:NtlmAuthentication xmlns:http="http://schemas.microsoft.com/ws/06/2004/policy/http"/>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsdl:import namespace="http://www.arkivverket.no/Noark/Exchange"
                 location="EDUImport.wsdl"/>
    <wsdl:types/>
    <wsdl:binding name="BasicHttpBinding_IEDUImport" type="i0:IEDUImport">
        <wsp:PolicyReference URI="#BasicHttpBinding_IEDUImport_policy"/>
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="GetCanReceiveMessage">
            <soap:operation soapAction="http://www.arkivverket.no/Noark/Exchange/IEDUImport/GetCanReceiveMessage"
                            style="document"/>
            <wsdl:input name="GetCanReceiveMessageRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="GetCanReceiveMessageResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="PutMessage">
            <soap:operation soapAction="http://www.arkivverket.no/Noark/Exchange/IEDUImport/PutMessage"
                            style="document"/>
            <wsdl:input name="PutMessageRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="PutMessageResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="EDUImportService">
        <wsdl:port name="BasicHttpBinding_IEDUImport" binding="tns:BasicHttpBinding_IEDUImport">
            <soap:address location="http://test-sakark01:8088/SI.WS.Core/Integration/EDUImport.svc/EDUImportService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
