
package no.arkivverket.noark.exchange;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "noarkExchange", targetNamespace = "http://www.arkivverket.no/Noark/Exchange", wsdlLocation = "http://muv-knutepunkt.herokuapp.com/noarkExchange?wsdl")
public class NoarkExchange
    extends Service
{

    private final static URL NOARKEXCHANGE_WSDL_LOCATION;
    private final static WebServiceException NOARKEXCHANGE_EXCEPTION;
    private final static QName NOARKEXCHANGE_QNAME = new QName("http://www.arkivverket.no/Noark/Exchange", "noarkExchange");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://muv-knutepunkt.herokuapp.com/noarkExchange?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOARKEXCHANGE_WSDL_LOCATION = url;
        NOARKEXCHANGE_EXCEPTION = e;
    }

    public NoarkExchange() {
        super(__getWsdlLocation(), NOARKEXCHANGE_QNAME);
    }

    public NoarkExchange(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOARKEXCHANGE_QNAME, features);
    }

    public NoarkExchange(URL wsdlLocation) {
        super(wsdlLocation, NOARKEXCHANGE_QNAME);
    }

    public NoarkExchange(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOARKEXCHANGE_QNAME, features);
    }

    public NoarkExchange(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NoarkExchange(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SOAPport
     */
    @WebEndpoint(name = "NoarkExchangePort")
    public SOAPport getNoarkExchangePort() {
        return super.getPort(new QName("http://www.arkivverket.no/Noark/Exchange", "NoarkExchangePort"), SOAPport.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOAPport
     */
    @WebEndpoint(name = "NoarkExchangePort")
    public SOAPport getNoarkExchangePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.arkivverket.no/Noark/Exchange", "NoarkExchangePort"), SOAPport.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOARKEXCHANGE_EXCEPTION!= null) {
            throw NOARKEXCHANGE_EXCEPTION;
        }
        return NOARKEXCHANGE_WSDL_LOCATION;
    }

}
