
package no.arkivverket.noark.exchange;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import no.arkivverket.noark.exchange.types.GetCanReceiveMessageRequestType;
import no.arkivverket.noark.exchange.types.GetCanReceiveMessageResponseType;
import no.arkivverket.noark.exchange.types.ObjectFactory;
import no.arkivverket.noark.exchange.types.PutMessageRequestType;
import no.arkivverket.noark.exchange.types.PutMessageResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SOAPport", targetNamespace = "http://www.arkivverket.no/Noark/Exchange")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SOAPport {


    /**
     * 
     * @param getCanReceiveMessageRequest
     * @return
     *     returns no.arkivverket.noark.exchange.types.GetCanReceiveMessageResponseType
     */
    @WebMethod(operationName = "GetCanReceiveMessage")
    @WebResult(name = "GetCanReceiveMessageResponse", targetNamespace = "http://www.arkivverket.no/Noark/Exchange/types", partName = "getCanReceiveMessageResponse")
    public GetCanReceiveMessageResponseType getCanReceiveMessage(
        @WebParam(name = "GetCanReceiveMessageRequest", targetNamespace = "http://www.arkivverket.no/Noark/Exchange/types", partName = "getCanReceiveMessageRequest")
        GetCanReceiveMessageRequestType getCanReceiveMessageRequest);

    /**
     * 
     * @param putMessageRequest
     * @return
     *     returns no.arkivverket.noark.exchange.types.PutMessageResponseType
     */
    @WebMethod(operationName = "PutMessage")
    @WebResult(name = "PutMessageResponse", targetNamespace = "http://www.arkivverket.no/Noark/Exchange/types", partName = "putMessageResponse")
    public PutMessageResponseType putMessage(
        @WebParam(name = "PutMessageRequest", targetNamespace = "http://www.arkivverket.no/Noark/Exchange/types", partName = "putMessageRequest")
        PutMessageRequestType putMessageRequest);

}
