info:
  version: ${pom.version}
server:
  port: 8090
spring:
  application:
    name: 'Monitor-UI-Localhost'
  cloud:
    config:
      enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka/'

---

spring:
    profiles: docker
    application:
      name: 'Monitor-UI-Docker'
    cloud:
      config:
        enabled: false
server:
  port: 8090
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: 'http://eurekaserver:8761/eureka/'
info:
  version: ${pom.version}
