//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 01:16:47 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uri.etsi.org/01903/v1.3.2#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package no.difi.meldingsutveksling.domain.xades;
