management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /manage
    enabled-by-default: 'true'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: 'true'
  health:
    readinessState:
      enabled: 'true'
    livenessState:
      enabled: 'true'
  info:
    git:
      mode: full
logging:
  level:
    'no':
      digipost:
        api:
          MessageSender: WARN
      difi:
        sdp:
          client2:
            internal:
              DigipostMessageSenderFacade: WARN
        asic: WARN
    org:
      springframework:
        oxm:
          jaxb:
            Jaxb2Marshaller: WARN
    mf:
      logger:
        translog: WARN
    com:
      microsoft:
        azure:
          servicebus:
            primitives:
              CoreMessageReceiver: ERROR
      netflix:
        discovery:
          shared:
            resolver:
              aws:
                ConfigClusterResolver: WARN
eureka:
  client:
    healthcheck:
      enabled: 'false'
    fetch-registry: 'false'
    enabled: 'true'
  instance:
    metadataMap:
      pr: ${pullrequest}
      orgnumber: ${difi.move.org.number}
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}:${difi.move.org.number}
      branch: ${scmBranch}
      commitId: ${buildNumber}
      version: '@project.version@'
    instance-id: ${difi.move.org.number}:${spring.cloud.client.hostname}:${server.port}
difi:
  move:
    fiks:
      io:
        default-ttl-hours: ${difi.move.nextmove.default-ttl-hours}
        api-host: api.fiks.test.ks.no
        upload-size-limit: 2GB
        host: io.fiks.test.ks.no
      ut:
        username: ''
        default-ttl-hours: ${difi.move.nextmove.default-ttl-hours}
        password: ''
        endpointUrl: https://test.svarut.ks.no/tjenester/forsendelseservice/ForsendelsesServiceV9
        upload-size-limit: 1GB
        kun-digital-levering: 'false'
      keystore:
        lockProvider: ${difi.move.org.keystore.lockProvider}
        password: ${difi.move.org.keystore.password}
        alias: ${difi.move.org.keystore.alias}
        type: ${difi.move.org.keystore.type}
        path: ${difi.move.org.keystore.path}
      inn:
        readTimeout: '30000'
        process: urn:no:difi:profile:arkivmelding:administrasjon:ver1.0
        password: ''
        enable: ${difi.move.feature.enableDPF}
        username: ''
        mailOnError: 'true'
        connectTimeout: '10000'
        document-type: urn:no:difi:arkivmelding:xsd::arkivmelding
        fallback-sender-org-nr: '999999999'
        baseUrl: https://svarut.ks.no/tjenester/svarinn
        orgnr: ${difi.move.org.number}
        mailSubject: Melding hentet fra SvarInn med utilstrekkelig metadata for levering
          via BestEdu
      pollingrate: '900000'
    feature:
      enableDsfPrintLookup: 'true'
      mailErrorStatus: 'false'
      enable-auth: ${difi.security.enable:false}
      forwardReceivedAppReceipts: 'true'
      cryptoMessagePersister: 'true'
      enableDPFIO: 'false'
      enableReceipts: 'true'
      enableDPE: 'false'
      enableDPF: 'false'
      enableDPI: 'false'
      enableQueue: 'true'
      enableDPO: 'true'
      enableDPV: 'false'
      retryOnDeadLock: 'true'
    nextmove:
      status-document-type: urn:no:difi:eformidling:xsd::status
      apply-zip-header-patch: 'false'
      serviceBus:
        pollingrate: '20000'
        readMaxMessages: '50'
        batchRead: 'false'
        mode: innsyn
        baseUrl: efm-dpe-qa.servicebus.windows.net
        sasKeyName: MoveDPE-pilotPolicy
        enable: ${difi.move.feature.enableDPE}
        default-ttl-hours: ${difi.move.nextmove.default-ttl-hours}
        useHttps: 'true'
        sasToken: <token>
        connectTimeout: '15000'
      default-ttl-hours: '24'
      ttlPollingrate: '30000'
      status-services: DPO,DPE
      statusPollingCron: 0 * * * * *
      service-bus:
        upload-size-limit: 2MB
      filedir: messages
      useDbPersistence: 'false'
      lockTimeoutMinutes: '5'
      statusPollingPageSize: '2000'
    dpi:
      timeout:
        read: '60000'
        write: '60000'
        connect: '5000'
      uri: https://srest.qa.dataplatfor.ms/dpi
      keystore:
        password: ${difi.move.org.keystore.password}
        type: ${difi.move.org.keystore.type}
        alias: ${difi.move.org.keystore.alias}
        lockProvider: ${difi.move.org.keystore.lockProvider}
        path: ${difi.move.org.keystore.path}
      clientMaxConnectionPoolSize: '10'
      oidc:
        url: ${difi.move.oidc.url}
        keystore:
          password: ${difi.move.dpi.keystore.password}
          path: ${difi.move.dpi.keystore.path}
          lockProvider: ${difi.move.dpi.keystore.lockProvider}
          type: ${difi.move.dpi.keystore.type}
          alias: ${difi.move.dpi.keystore.alias}
        clientId: ${difi.move.oidc.clientId}
        enable: ${difi.move.oidc.enable}
        audience: ${difi.move.oidc.audience}
        scopes: digitalpostinnbygger:send
      c2-type: web
      initialBufferSize: '100000'
      language: 'NO'
      krr-print-url: https://test.kontaktregisteret.no/rest/v2/printSertifikat
      printSettings:
        returnType: SHREDDING
        inkType: BLACK_WHITE
        shippingType: ECONOMY
      client-type: json
      pollingrate: '10000'
      mpcId: no_difi_move_integrasjonspunkt
      priority: NORMAL
      mpcConcurrency: '1'
      temporary-file-threshold: '1000000'
      pollWithoutAvsenderidentifikator: 'true'
      certificate:
        recipe: classpath:/pki/recipe-dpi-move-difiSigned.xml
      default-ttl-hours: ${difi.move.nextmove.default-ttl-hours}
      upload-size-limit: 150MB
    einnsyn:
      default-innsynskrav-document-type: urn:no:difi:einnsyn:xsd::innsynskrav
      default-journal-document-type: urn:no:difi:einnsyn:xsd::publisering
      receipt-process: urn:no:difi:profile:einnsyn:response:ver1.0
      default-innsynskrav-process: urn:no:difi:profile:einnsyn:innsynskrav:ver1.0
      default-journal-process: urn:no:difi:profile:einnsyn:journalpost:ver1.0
    queue:
      maximum-retry-hours: '100'
      concurrency: '10'
      dlq-name: ActiveMQ.DLQ
      noark-name: noark
      nextmove-name: nextmove
    org:
      keystore:
        lockProvider: 'false'
        type: jks
    dpv:
      notifySms: 'true'
      upload-size-limit: 200MB
      default-ttl-hours: ${difi.move.nextmove.default-ttl-hours}
      enableDueDate: 'true'
      notification-text: '$reporteeName$: Du har mottatt en melding fra $reporterName$.'
      sensitive-notification-text: $reporteeName$, har mottatt en taushetsbelagt melding
        fra $reporterName$. For å få tilgang til meldingen, er det nødvendig at noen
        i $reporteeName$ har fått tildelt rollen «Taushetsbelagt post fra det offentlige»
        i Altinn. Dersom dere er usikre på om noen har slik tilgang, anbefaler vi
        sterkt at dette sjekkes. Les mer om å gi tilgang til rollen «Taushetsbelagt
        post» på Altinns nettsider.
      endpointUrl: https://tt02.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternal.svc
      sensitive-service-code: '5504'
      daysToReply: '7'
      allow-forwarding: 'true'
      notifyEmail: 'true'
    dpo:
      brokerserviceUrl: https://tt02.altinn.no/ServiceEngineExternal/BrokerServiceExternalBasic.svc?wsdl
      requestTimeout: '30000'
      streamingserviceUrl: https://tt02.altinn.no/ServiceEngineExternal/BrokerServiceExternalBasicStreamed.svc?wsdl
      default-ttl-hours: ${difi.move.nextmove.default-ttl-hours}
      serviceCode: '4192'
      upload-size-limit: 1GB
      connectTimeout: '3000'
      serviceEditionCode: '270815'
    arkivmelding:
      generate-receipts: 'true'
      dpv-default-process: ${difi.move.arkivmelding.default-process}
      default-document-type: urn:no:difi:arkivmelding:xsd::arkivmelding
      default-process: urn:no:difi:profile:arkivmelding:administrasjon:ver1.0
      receipt-process: urn:no:difi:profile:arkivmelding:response:ver1.0
      receipt-document-type: urn:no:difi:arkivmelding:xsd::arkivmelding_kvittering
    oidc:
      url: https://maskinporten.no/token
      clientIdPrefix: MOVE_IP_
      audience: https://maskinporten.no/
      keystore:
        type: ${difi.move.org.keystore.type}
        lockProvider: ${difi.move.org.keystore.lockProvider}
        path: ${difi.move.org.keystore.path}
        password: ${difi.move.org.keystore.password}
        alias: ${difi.move.org.keystore.alias}
      enable: 'true'
      clientId: ${difi.move.oidc.clientIdPrefix}${difi.move.org.number}
    deadlock:
      retryCount: '5'
      delay: '1000'
    ntp:
      host: time.google.com
      disable: 'false'
    sign:
      enable: 'true'
      jwkUrl: ${difi.move.serviceregistryEndpoint}/jwk
    serviceregistryEndpoint: https://meldingsutveksling.difi.no/serviceregistry
    avtalt:
      receipt-process: urn:no:difi:profile:avtalt:response:ver1.0
    webhooks:
      connectTimeout: '10000'
      readTimeout: '10000'
  activemq:
    broker-url: vm://localhost
  datasource:
    url: jdbc:h2:file:./integrasjonspunkt
server:
  ssl:
    key-store: ${difi.ssl.key-store}
    key-alias: ${difi.ssl.key-alias}
    key-store-type: ${difi.ssl.key-store-type:JKS}
    key-store-password: ${difi.ssl.key-store-password}
    enabled: ${difi.ssl.enabled:false}
  port: '9093'
  connection-timeout: '300000'
spring:
  datasource:
    url: ${difi.datasource.url}
    hikari:
      autoCommit: 'false'
      maximum-pool-size: '50'
    password: ${difi.datasource.password:}
    username: ${difi.datasource.username:sa}
  liquibase:
    enabled: 'true'
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  activemq:
    password: ${difi.activemq.password:}
    user: ${difi.activemq.user:}
    broker-url: ${difi.activemq.broker-url}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Oslo
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      javax:
        persistence:
          validation:
            mode: none
    open-in-view: 'false'
  security:
    user:
      password: ${difi.security.user.password:#{null}}
      name: ${difi.security.user.name:#{null}}
  profiles:
    active: production
