eureka:
  client:
    region: DIFI-MOVE-staging
    serviceUrl:
      defaultZone: https://eformidling.dev/discovery/eureka
difi:
  move:
    feature:
      enableDPE: 'true'
      enableDPF: 'false'
      enableDPI: 'false'
      enableDPO: 'false'
      enableDPV: 'false'
    serviceregistryEndpoint: https://qa-meldingsutveksling.difi.no/serviceregistry
    oidc:
      keystore:
        alias: ${difi.move.org.keystore.alias}
        path: ${difi.move.org.keystore.path}
        password: ${difi.move.org.keystore.password}
      url: https://test.maskinporten.no/token
      audience: https://test.maskinporten.no/
    dpo:
      streamingserviceUrl: https://www.altinn.no/ServiceEngineExternal/BrokerServiceExternalBasicStreamed.svc?wsdl
      brokerserviceUrl: https://www.altinn.no/ServiceEngineExternal/BrokerServiceExternalBasic.svc?wsdl
    arkivmelding:
      generate-receipts: 'false'
    dpi:
      endpoint: https://qaoffentlig.meldingsformidler.digipost.no/api/ebms
      certificate:
        recipe: classpath:/pki/recipe-dpi-norway-test.xml
      mpcId: no_difi_move_integrasjonspunkt-staging
    fiks:
      inn:
        baseUrl: https://test.svarut.ks.no/tjenester/svarinn
spring:
  config:
    import: optional:file:integrasjonspunkt-local.yml
