difi:
  move:
    oidc:
      enable: false
    dpi:
      uri: http://localhost:8080/api/c2
      client-type: json
      endpoint: http://localhost:8080/as4
      certificate:
        recipe: classpath:/pki/recipe-dpi-move-difiSigned.xml
      oidc:
        mock:
          token: foo123
    dpo:
      streamingserviceUrl: http://localhost:8001/dpo/ServiceEngineExternal/BrokerServiceExternalBasicStreamed.svc?wsdl
      brokerserviceUrl: http://localhost:8001/dpo/ServiceEngineExternal/BrokerServiceExternalBasic.svc?wsdl
    dpv:
      password: whatever
      username: whatever
      endpointUrl: http://localhost:8001/dpv/
    fiks:
      ut:
        password: password
        endpointUrl: http://localhost:8001/dpf
        username: username
      inn:
        username: 910075918
        mailOnError: false
        password: password
        baseUrl: http://localhost:8001/svarinn
      pollingrate: 10000
    org:
      number: 910075918
      keystore:
        password: changeit
        path: cloud:mock.jks
        alias: 910075918
    sign:
      enable: false
    feature:
      enableDPE: true
      enableDPF: true
      enableDPI: true
      enableDPO: true
      enableDPV: true
    serviceregistryEndpoint: http://localhost:8090
    nextmove:
      serviceBus:
        baseUrl: localhost:8001/dpe
        useHttps: false
app:
  logger:
    enableLogstash: false
eureka:
  client:
    enabled: false
