difi:
  move:
    org:
      keystore:
        password: changeit
        path: crt/test-certificates.jks
        alias: '974720760'
    serviceregistryEndpoint: https://eformidling.dev/adressetjeneste
    oidc:
      keystore:
        alias: digdir-test-eformidling
        path: changeit
        password: changeit
      url: https://test.maskinporten.no/token
      audience: https://test.maskinporten.no/
      clientId: test_move
    dpi:
      endpoint: https://qaoffentlig.meldingsformidler.digipost.no/api/ebms
      mpcId: no_difi_move_integrasjonspunkt-dev
    fiks:
      pollingrate: '15000'
      inn:
        baseUrl: https://test.svarut.ks.no/tjenester/svarinn
    nextmove:
      serviceBus:
        pollingrate: '5000'
spring:
  config:
    import: optional:file:integrasjonspunkt-local.yml
logging:
  level:
    'no':
      difi:
        sdp:
          client2:
            internal:
              DigipostMessageSenderFacade: TRACE
    mf:
      logger:
        translog: TRACE
    org:
      springframework:
        ws:
          client:
            MessageTracing: INFO
          server:
            MessageTracing: INFO
eureka:
  client:
    serviceUrl:
      defaultZone: https://eformidling.dev/discovery/eureka
