
package no.difi.meldingsutveksling.noarkexchange.schema.receive;

import javax.jws.WebService;
import javax.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "ReceivePort", serviceName = "receive", targetNamespace = "http://noarkexchange.meldingsutveksling.difi.no/", wsdlLocation = "file:/Users/steinbjarne/projects/meldingsutveksling-mellom-offentlige-virksomheter/praktiskprove/noarkexchange/src/wsdl/IntegrasjonspunktReceive.wsdl", endpointInterface = "no.difi.meldingsutveksling.noarkexchange.schema.receive.SOAReceivePort")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class receive_ReceivePortImpl
    implements SOAReceivePort
{


    public receive_ReceivePortImpl() {
    }

    /**
     * 
     * @param receiveResponse
     * @return
     *     returns no.difi.meldingsutveksling.noarkexchange.schema.receive.CorrelationInformation
     */
    public CorrelationInformation receive(StandardBusinessDocument receiveResponse) {
        //replace with your impl here
        return null;
    }

}
