//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 12:23:12 PM CET 
//


package no.difi.meldingsutveksling.domain.sbdh;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import no.difi.meldingsutveksling.ApiType;
import no.difi.meldingsutveksling.validation.IsDocumentType;
import no.difi.meldingsutveksling.validation.UUID;
import no.difi.meldingsutveksling.xml.OffsetDateTimeAdapter;

import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * <p>Java class for DocumentIdentification complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DocumentIdentification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Standard" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TypeVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InstanceIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MultipleType" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CreationDateAndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentIdentification", propOrder = {
        "standard",
        "typeVersion",
        "instanceIdentifier",
        "type",
        "multipleType",
        "creationDateAndTime"
})
@Data
@Embeddable
public class DocumentIdentification implements Serializable {

    @XmlElement(name = "Standard", required = true)
    @NotNull
    @ApiModelProperty(
            value = "Document standard",
            example = "urn:no:difi:arkivmelding:xsd::arkivmelding",
            required = true
    )
    protected String standard;

    @XmlElement(name = "TypeVersion", required = true)
    @NotNull
    @ApiModelProperty(
            example = "2.0",
            required = true
    )
    protected String typeVersion;

    @XmlElement(name = "InstanceIdentifier", required = true)
    @UUID
    @ApiModelProperty(
            value = "The conversation ID. Usually a UUID",
            example = "90c0bacf-c233-4a54-96fc-e205b79862d9"
    )
    protected String instanceIdentifier;

    @XmlElement(name = "Type", required = true)
    @NotNull
    @IsDocumentType(ApiType.NEXTMOVE)
    @ApiModelProperty(
            value = "Document type. This is always identical to the last part of the standard and must correspond with the name of the payload property.",
            example = "arkivmelding",
            required = true
    )
    protected String type;

    @XmlElement(name = "MultipleType")
    protected Boolean multipleType;

    @XmlElement(name = "CreationDateAndTime", required = true)
    @XmlSchemaType(name = "dateTime")
    @XmlJavaTypeAdapter(OffsetDateTimeAdapter.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING)
    @Past
    @ApiModelProperty(
            value = "When the message was created.",
            example = "2019-05-10T01:31:52+02:00"
    )
    protected OffsetDateTime creationDateAndTime;
}
