//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 12:23:12 PM CET 
//


package no.difi.meldingsutveksling.domain.sbdh;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;
import no.difi.meldingsutveksling.domain.Organisasjonsnummer;
import no.difi.meldingsutveksling.validation.EqualToProperty;
import no.difi.meldingsutveksling.validation.InServiceRegistry;
import no.difi.meldingsutveksling.validation.group.ValidationGroups;
import no.difi.meldingsutveksling.validation.group.sequenceprovider.PartnerIdentificationGroupSequenceProvider;
import org.hibernate.annotations.Parent;
import org.hibernate.validator.group.GroupSequenceProvider;

import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for PartnerIdentification complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PartnerIdentification">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="Authority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartnerIdentification", propOrder = {
        "value"
})
@EqualsAndHashCode(exclude = "partner")
@Getter
@Setter
@ToString(exclude = "partner")
@RequiredArgsConstructor
@Embeddable
@GroupSequenceProvider(value = PartnerIdentificationGroupSequenceProvider.class)
public class PartnerIdentification implements Serializable {

    @XmlTransient
    @JsonIgnore
    @Parent
    private Partner partner;

    @XmlValue
    @InServiceRegistry
    @EqualToProperty(value = "difi.move.org.number", groups = ValidationGroups.Partner.Sender.class)
    @NotNull
    @ApiModelProperty(
            value = "Identifier",
            example = "0192:987654321",
            required = true
    )
    protected String value;

    @XmlAttribute(name = "Authority")
    @NotNull
    @ApiModelProperty(
            value = "Authority",
            example = "iso6523-actorid-upis",
            required = true
    )
    protected String authority;

    @JsonIgnore
    String getStrippedValue() {
        if (value == null) {
            return null;
        }

        return Organisasjonsnummer.isIso6523(value) ? Organisasjonsnummer.fromIso6523(value).toString() : value;
    }


}
