//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 12:23:12 PM CET 
//


package no.difi.meldingsutveksling.domain.sbdh;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import net.logstash.logback.marker.LogstashMarker;
import no.difi.meldingsutveksling.domain.MeldingsUtvekslingRuntimeException;
import no.difi.meldingsutveksling.domain.MessageInfo;
import no.difi.meldingsutveksling.domain.Organisasjonsnummer;
import no.difi.meldingsutveksling.nextmove.*;
import no.difi.meldingsutveksling.validation.InstanceOf;
import no.difi.meldingsutveksling.validation.group.ValidationGroups;
import no.difi.meldingsutveksling.validation.group.sequenceprovider.StandardBusinessDocumentGroupSequenceProvider;
import org.hibernate.validator.group.GroupSequenceProvider;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.*;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.Set;


/**
 * Java class for StandardBusinessDocument complex type.
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="StandardBusinessDocument">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader}StandardBusinessDocumentHeader" minOccurs="0"/>
 *         <any processContents='lax' namespace='##other'/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StandardBusinessDocument", propOrder = {
        "standardBusinessDocumentHeader",
        "any"
})
@Getter
@Setter
@ToString
@JsonSerialize(using = NextMoveMessageSerializer.class)
@GroupSequenceProvider(StandardBusinessDocumentGroupSequenceProvider.class)
public class StandardBusinessDocument {

    @XmlElement(name = "StandardBusinessDocumentHeader")
    @NotNull
    @Valid
    private StandardBusinessDocumentHeader standardBusinessDocumentHeader;

    @XmlAnyElement(lax = true)
    @JsonDeserialize(using = NextMoveMessageDeserializer.class)
    @JsonAlias({"fiksio", "arkivmelding", "arkivmelding_kvittering", "avtalt", "digital", "digital_dpv", "print", "innsynskrav", "publisering", "einnsyn_kvittering", "status"})
    @NotNull
    @InstanceOf(value = FiksIoMessage.class, groups = ValidationGroups.MessageType.FiksIo.class)
    @InstanceOf(value = ArkivmeldingMessage.class, groups = ValidationGroups.MessageType.Arkivmelding.class)
    @InstanceOf(value = AvtaltMessage.class, groups = ValidationGroups.MessageType.Avtalt.class)
    @InstanceOf(value = DpiDigitalMessage.class, groups = ValidationGroups.MessageType.Digital.class)
    @InstanceOf(value = DigitalDpvMessage.class, groups = ValidationGroups.MessageType.DigitalDpv.class)
    @InstanceOf(value = DpiPrintMessage.class, groups = ValidationGroups.MessageType.Print.class)
    @InstanceOf(value = InnsynskravMessage.class, groups = ValidationGroups.MessageType.Innsynskrav.class)
    @InstanceOf(value = PubliseringMessage.class, groups = ValidationGroups.MessageType.Publisering.class)
    @Valid
    private Object any;

    @JsonIgnore
    public BusinessMessage getBusinessMessage() {
        return (BusinessMessage) getAny();
    }

    @JsonIgnore
    public MessageInfo getMessageInfo() {
        return new MessageInfo(getMessageType(), getReceiverIdentifier(), getSenderIdentifier(), getJournalPostId(), getConversationId(), getDocumentId());
    }

    @JsonIgnore
    public Organisasjonsnummer getSender() {
        return getStandardBusinessDocumentHeader().getFirstSender()
                .map(Partner::getIdentifier)
                .map(PartnerIdentification::getAsOrganisasjonsnummer)
                .orElse(null);
    }

    @JsonIgnore
    public String getSenderIdentifier() {
        return getStandardBusinessDocumentHeader().getFirstSender()
                .map(Partner::getIdentifier)
                .map(PartnerIdentification::getStrippedValue)
                .orElse(null);
    }

    @JsonIgnore
    public Optional<String> getPartIdentifier() {
        return getStandardBusinessDocumentHeader().getFirstSender()
                .map(Partner::getIdentifier)
                .map(PartnerIdentification::getPaaVegneAvValue);
    }

    @JsonIgnore
    public String getSenderOrgnr() {
        return getPartIdentifier().orElse(getSenderIdentifier());
    }

    @JsonIgnore
    public Organisasjonsnummer getReceiver() {
        return getStandardBusinessDocumentHeader().getFirstReceiver()
                .map(Partner::getIdentifier)
                .map(PartnerIdentification::getAsOrganisasjonsnummer)
                .orElse(null);
    }

    @JsonIgnore
    public String getReceiverIdentifier() {
        return getStandardBusinessDocumentHeader().getFirstReceiver()
                .map(Partner::getIdentifier)
                .map(PartnerIdentification::getStrippedValue)
                .orElse(null);
    }

    @JsonIgnore
    public final String getJournalPostId() {
        return findScope(ScopeType.JOURNALPOST_ID)
                .map(Scope::getInstanceIdentifier)
                .orElse("");
    }

    @JsonIgnore
    public String getConversationId() {
        return getOptionalConversationId()
                .orElseThrow(MeldingsUtvekslingRuntimeException::new);
    }

    @JsonIgnore
    public Optional<String> getOptionalConversationId() {
        return findScope(ScopeType.CONVERSATION_ID)
                .map(Scope::getInstanceIdentifier);
    }

    @JsonIgnore
    public Set<Scope> getScopes() {
        return getStandardBusinessDocumentHeader()
                .getBusinessScope()
                .getScope();
    }

    public Scope getScope(ScopeType scopeType) {
        return findScope(scopeType)
                .orElseThrow(() -> new NextMoveRuntimeException(String.format("Missing scope %s", scopeType.name())));
    }

    public Optional<Scope> findScope(ScopeType scopeType) {
        return getScopes()
                .stream()
                .filter(scope -> scopeType.toString().equals(scope.getType()) || scopeType.name().equals(scope.getType()))
                .findAny();
    }

    @JsonIgnore
    public String getMessageType() {
        return getStandardBusinessDocumentHeader().getDocumentIdentification().getType();
    }

    @JsonIgnore
    public String getDocumentType() {
        return getStandardBusinessDocumentHeader().getDocumentIdentification().getStandard();
    }

    @JsonIgnore
    public String getProcess() {
        return getScope(ScopeType.CONVERSATION_ID)
                .getIdentifier();
    }

    @JsonIgnore
    public String getDocumentId() {
        return getStandardBusinessDocumentHeader().getDocumentIdentification().getInstanceIdentifier();
    }

    @JsonIgnore
    public String getMessageId() {
        return getDocumentId();
    }

    @JsonIgnore
    public Optional<String> getOptionalMessageId() {
        return Optional.ofNullable(getDocumentId());
    }

    public LogstashMarker createLogstashMarkers() {
        return getMessageInfo().createLogstashMarkers();
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getExpectedResponseDateTime() {
        return getScope(ScopeType.CONVERSATION_ID)
                .getScopeInformation()
                .stream().findFirst()
                .map(CorrelationInformation::getExpectedResponseDateTime);
    }
}
