
package no.difi.meldingsutveksling.noarkexchange;

import no.difi.meldingsutveksling.noarkexchange.schema.*;

import javax.jws.WebService;
import javax.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 */
@WebService(portName = "noarkExchangePort", serviceName = "noarkExchange", targetNamespace = "http://www.arkivverket.no/Noark/Exchange", wsdlLocation = "file:/Users/glennbech/dev/meldingsutvikling-mellom-offentlige-virksomheter/praktiskprove/knutepunkt/src/main/webapp/WEB-INF/wsdl/noarkExchange.wsdl", endpointInterface = "no.difi.meldingsutveksling.noarkexchange.schema.SOAPport")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class KnutepunktImpl implements SOAPport {

    public KnutepunktImpl() {
    }

    /**
     * @param getCanReceiveMessageRequest
     * @return returns no.difi.meldingsutveksling.noarkexchange.schema.GetCanReceiveMessageResponseType
     */
    public GetCanReceiveMessageResponseType getCanReceiveMessage(GetCanReceiveMessageRequestType getCanReceiveMessageRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * @param putMessageRequest
     * @return returns no.difi.meldingsutveksling.noarkexchange.schema.PutMessageResponseType
     */
    public PutMessageResponseType putMessage(PutMessageRequestType putMessageRequest) {
        PutMessageRequestType putMessage = new PutMessageRequestType();
        return null;
    }

}
