name: Maven build and test

on:
  push:
    branches-ignore: [main]

jobs:
  call-workflow-maven-build:
    if: ${{ !contains(github.event.head_commit.message, '[run-ci]') }}
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-build.yml@MOVE-4223
    with:
      java-version: 21
      application-path: integrasjonspunkt/
    secrets: inherit

