name: CI Workflow

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [ ] # Empty list ensures PRs are not triggered. Trigger nytt bygg..

jobs:
  #also deploys to maven central/ossrh
  build-and-deploy-libs:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-install-deploy-lib.yml@add_fetch_depth_to_mvn_deploy_workflow
    with:
      java-version: 8
      sbom-path: integrasjonspunkt/target
    secrets: inherit

#    bygge image, laste opp image relevant plass
#    deploye til DEV + evt TEST