name: Maven build and test

on:
  push:
    branches-ignore: [main]

jobs:
  call-workflow-maven-build:
    if: !contains(github.event.head_commit.message, '[run-ci]') && !contains(github.event.head_commit.message, '[docker]')
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-build.yml@main
    with:
      java-version: 21
      application-path: integrasjonspunkt/
    secrets: inherit

