name: Release Integrasjonspunkt v2.x

on:
  release:
    types:
      - created

jobs:
  build-and-deploy-libs:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-install-deploy-lib.yml@PF-2334-improve-trivyignore-detection
    with:
      java-version: 8
      sbom-path: integrasjonspunkt/target
      fetch-depth: 0
      application-path: integrasjonspunkt/
    secrets: inherit

  build-and-deploy-image:
    needs: build-and-deploy-libs
    uses: felleslosninger/github-workflows/.github/workflows/ci-docker-build-publish-integrasjonspunkt.yml@PF-2334-improve-trivyignore-detection
    with:
      slack-channel-id: C05NLQCFR41
      package-version: 2.28.8
      java-version: 8
    secrets: inherit
